/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vansh
 */
public class CricScoreboard extends javax.swing.JFrame {

    /**
     * Creates new form CricScoreboard
     */
    public CricScoreboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtf1 = new javax.swing.JTextField();
        jtf2 = new javax.swing.JTextField();
        jtf3 = new javax.swing.JTextField();
        jtf4 = new javax.swing.JTextField();
        jtf5 = new javax.swing.JTextField();
        jtf6 = new javax.swing.JTextField();
        jtf7 = new javax.swing.JTextField();
        jtf8 = new javax.swing.JTextField();
        jtf9 = new javax.swing.JTextField();
        jtf10 = new javax.swing.JTextField();
        jtf11 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA3 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtf12 = new javax.swing.JTextField();
        jtf13 = new javax.swing.JTextField();
        jtf14 = new javax.swing.JTextField();
        jtf15 = new javax.swing.JTextField();
        jtf16 = new javax.swing.JTextField();
        jtf17 = new javax.swing.JTextField();
        jtf18 = new javax.swing.JTextField();
        jtf19 = new javax.swing.JTextField();
        jtf20 = new javax.swing.JTextField();
        jtf21 = new javax.swing.JTextField();
        jtf22 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLB1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        run = new javax.swing.JTextField();
        wicket = new javax.swing.JTextField();
        overs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        score1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        score2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("TEAM 1 SELECTION");

        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "INDIA", "PAKISTAN", "NEW ZEALAND", "AUSTRALIA", "ENGLAND" }));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("TEAM@ 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("TEAM PLATYING ELEVEN");

        jtf1.setBackground(new java.awt.Color(102, 255, 102));
        jtf1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf1.setText("                                    ");

        jtf2.setBackground(new java.awt.Color(102, 255, 102));
        jtf2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf2.setText("                                    ");

        jtf3.setBackground(new java.awt.Color(102, 255, 102));
        jtf3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf3.setText("                                    ");

        jtf4.setBackground(new java.awt.Color(102, 255, 102));
        jtf4.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf4.setText("                                    ");

        jtf5.setBackground(new java.awt.Color(102, 255, 102));
        jtf5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf5.setText("                                    ");

        jtf6.setBackground(new java.awt.Color(102, 255, 102));
        jtf6.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf6.setText("                                    ");

        jtf7.setBackground(new java.awt.Color(102, 255, 102));
        jtf7.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf7.setText("                                    ");

        jtf8.setBackground(new java.awt.Color(102, 255, 102));
        jtf8.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf8.setText("                                    ");

        jtf9.setBackground(new java.awt.Color(102, 255, 102));
        jtf9.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf9.setText("                                    ");

        jtf10.setBackground(new java.awt.Color(102, 255, 102));
        jtf10.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf10.setText("                                    ");

        jtf11.setBackground(new java.awt.Color(102, 255, 102));
        jtf11.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf11.setText("                                    ");

        jTA1.setEditable(false);
        jTA1.setColumns(20);
        jTA1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTA1.setRows(5);
        jScrollPane2.setViewportView(jTA1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtf11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTA3.setEditable(false);
        jTA3.setBackground(new java.awt.Color(255, 0, 51));
        jTA3.setColumns(20);
        jTA3.setRows(5);
        jScrollPane1.setViewportView(jTA3);

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel3.setText("TEAM 2 SELECTION");

        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "INDIA", "PAKISTAN", "NEW ZEALAND", "AUSTRALIA", "ENGLAND" }));

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("TEAM@ 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("TEAM PLAYING ELEVEN");

        jtf12.setEditable(false);
        jtf12.setBackground(new java.awt.Color(102, 255, 102));
        jtf12.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf12.setText("                                  ");

        jtf13.setEditable(false);
        jtf13.setBackground(new java.awt.Color(102, 255, 102));
        jtf13.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf13.setText("                                  ");

        jtf14.setEditable(false);
        jtf14.setBackground(new java.awt.Color(102, 255, 102));
        jtf14.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf14.setText("                                  ");

        jtf15.setEditable(false);
        jtf15.setBackground(new java.awt.Color(102, 255, 102));
        jtf15.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf15.setText("                                  ");

        jtf16.setEditable(false);
        jtf16.setBackground(new java.awt.Color(102, 255, 102));
        jtf16.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf16.setText("                                  ");

        jtf17.setEditable(false);
        jtf17.setBackground(new java.awt.Color(102, 255, 102));
        jtf17.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf17.setText("                                  ");

        jtf18.setEditable(false);
        jtf18.setBackground(new java.awt.Color(102, 255, 102));
        jtf18.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf18.setText("                                  ");

        jtf19.setEditable(false);
        jtf19.setBackground(new java.awt.Color(102, 255, 102));
        jtf19.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf19.setText("                                  ");

        jtf20.setEditable(false);
        jtf20.setBackground(new java.awt.Color(102, 255, 102));
        jtf20.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf20.setText("                                  ");

        jtf21.setEditable(false);
        jtf21.setBackground(new java.awt.Color(102, 255, 102));
        jtf21.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf21.setText("                                  ");

        jtf22.setEditable(false);
        jtf22.setBackground(new java.awt.Color(102, 255, 102));
        jtf22.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtf22.setText("                                  ");

        jTA2.setColumns(20);
        jTA2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTA2.setRows(5);
        jScrollPane3.setViewportView(jTA2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)))
                .addGap(52, 52, 52))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setText("TOS WON BY");

        jRadioButton1.setText("TEAM@ 1");

        jRadioButton2.setText("TEAM@ 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2))
        );

        jLabel6.setText("MATCH TYPE");

        jRadioButton3.setText("T20");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("ONE DAY");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setText("i");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLB1.setFont(new java.awt.Font("Pristina", 3, 36)); // NOI18N

        jButton4.setBackground(new java.awt.Color(51, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("0");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setText("3");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setText("4");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(51, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setText("5");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(51, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("6");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(51, 255, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton11.setText("WIDE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(51, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton12.setText("NO BALL");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(51, 255, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton13.setText("WICKET");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 255, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("OVER LIMIT");

        jlb2.setBackground(new java.awt.Color(102, 255, 102));
        jlb2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel9.setText("RUNS");

        jLabel10.setText("WICKET");

        jLabel11.setText("OVERS");

        run.setEditable(false);
        run.setText("                   ");

        wicket.setEditable(false);
        wicket.setText("                    ");

        overs.setEditable(false);
        overs.setText("                       ");

        jLabel12.setBackground(new java.awt.Color(255, 0, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("SCORE");

        jLabel13.setText("i");

        score1.setEditable(false);
        score1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        score1.setText("                ");

        jLabel14.setText("ii");

        score2.setEditable(false);
        score2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        score2.setText("                ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLB1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(wicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(run, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                    .addComponent(overs, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                                    .addComponent(jButton12))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(34, 34, 34)
                                                .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(9, 9, 9)
                                                .addComponent(score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(score2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 489, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jLB1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)
                                    .addComponent(jButton10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton11)
                                    .addComponent(jButton12)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(overs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(score2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
int ball,r=0,w=0,o=0,b=0,a=0,bb=0,c=0,balls;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(jCB1.getSelectedIndex()==1) 
{  jTA1.setText("***INDIA***");

    jtf1.setText("ROHIT SHARMA   VC");

    jtf2.setText("SHIKHAR DHAWAN");

    jtf3.setText("KL RAHUL");

    jtf4.setText("VIRAT KOHLI    C");

    jtf5.setText("RISHAB PANT    WK");

    jtf6.setText("ASHWIN");

    jtf7.setText("JADEJA");

    jtf8.setText("JASPRIT BUMRAH");

    jtf9.setText("BHUVNESHWAR");

    jtf10.setText("HARDIK PANDYA");

    jtf11.setText("CHAHAL");
}
else if(jCB1.getSelectedIndex()==2) 
{  jTA1.setText("***PAKISTAN***");

    jtf1.setText("BABAR AZAM   C");

    jtf2.setText("SHADAB KHAN   VC");

    jtf3.setText("MOHAMMAD RIZWAN");

    jtf4.setText("HAIDER ALI");

    jtf5.setText("AZHAR ALI");

    jtf6.setText("ABID ALI");

    jtf7.setText("SHAN MASOOD");

    jtf8.setText("IMAM-UL-HAQ");

    jtf9.setText("FAKHAR ZAMAN");

    jtf10.setText("FAWAD ALAM");

    jtf11.setText("ASIF ALI");    
 
}
else if(jCB1.getSelectedIndex()==3)
{   
    jTA1.setText("***NEW ZEALAND***");

    jtf1.setText("STEFAN MARINOVIC");

    jtf2.setText("MICHAEL WOUD   VC");

    jtf3.setText("KANE WILLIAMSON  C");

    jtf4.setText("TOMMY SMITH");

    jtf5.setText("BILL TUILOMA");

    jtf6.setText("TIM PAYNE");

    jtf7.setText("MARCO ROJAS");

    jtf8.setText("CHRIS WOOD");

    jtf9.setText("MAX MATTA");

    jtf10.setText("WILL YOUNG");

    jtf11.setText("JAMES NEESHAM");    
 
}
else if(jCB1.getSelectedIndex()==4)
{   
    jTA1.setText("**AUSTRALIA**");

    jtf1.setText("JOE BURNS");

    jtf2.setText("DAVID WARNER   VC");

    jtf3.setText("STEVE SMITH   C");

    jtf4.setText("SEAN ABBOT");

    jtf5.setText("MATCHELL MARSH");

    jtf6.setText("MARCUS STONIS");

    jtf7.setText("TIM PAINE");

    jtf8.setText("MATTHEW WADE");

    jtf9.setText("PAT CUMMINS");

    jtf10.setText("MITCHELL STAC");

    jtf11.setText("ADAM ZAMPA");    
 
}
else if(jCB1.getSelectedIndex()==5)
{   
    jTA1.setText("**ENGLAND**");

    jtf1.setText("JOE ROOT   C");

    jtf2.setText("TOM BANTON   VC");

    jtf3.setText("DAN LAWRENCE");

    jtf4.setText("JAMES VINCE");

    jtf5.setText("BEN FOAKES");

    jtf6.setText("MOEEN ALI");

    jtf7.setText("JAMES ANDERSON");

    jtf8.setText("JORFA ARCHER");

    jtf9.setText("TOM CURRAN");

    jtf10.setText("MARK WOOD");

    jtf11.setText("MATT PARKINSON");
}
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(jCB2.getSelectedIndex()==1) 
{  jTA2.setText("***INDIA***");

    jtf12.setText("ROHIT SHARMA   VC");

    jtf13.setText("SHIKHAR DHAWAN");

    jtf14.setText("KL RAHUL");

    jtf15.setText("VIRAT KOHLI    C");

    jtf16.setText("RISHAB PANT    WK");

    jtf17.setText("ASHWIN");

    jtf18.setText("JADEJA");

    jtf19.setText("JASPRIT BUMRAH");

    jtf20.setText("BHUVNESHWAR");

    jtf21.setText("HARDIK PANDYA");

    jtf22.setText("CHAHAL");
}
else if(jCB2.getSelectedIndex()==2) 
{  jTA2.setText("***PAKISTAN***");

    jtf12.setText("BABAR AZAM   C");

    jtf13.setText("SHADAB KHAN   VC");

    jtf14.setText("MOHAMMAD RIZWAN");

    jtf15.setText("HAIDER ALI");

    jtf16.setText("AZHAR ALI");

    jtf17.setText("ABID ALI");

    jtf18.setText("SHAN MASOOD");

    jtf19.setText("IMAM-UL-HAQ");

    jtf20.setText("FAKHAR ZAMAN");

    jtf21.setText("FAWAD ALAM");

    jtf22.setText("ASIF ALI");    
 
}
else if(jCB2.getSelectedIndex()==3)
{   
    jTA2.setText("***NEW ZEALAND***");

    jtf12.setText("STEFAN MARINOVIC");

    jtf13.setText("MICHAEL WOUD   VC");

    jtf14.setText("KANE WILLIAMSON  C");

    jtf15.setText("TOMMY SMITH");

    jtf16.setText("BILL TUILOMA");

    jtf17.setText("TIM PAYNE");

    jtf18.setText("MARCO ROJAS");

    jtf19.setText("CHRIS WOOD");

    jtf20.setText("MAX MATTA");

    jtf21.setText("WILL YOUNG");

    jtf22.setText("JAMES NEESHAM");    
 
}
else if(jCB2.getSelectedIndex()==4)
{   
    jTA2.setText("**AUSTRALIA**");

    jtf12.setText("JOE BURNS");

    jtf13.setText("DAVID WARNER   VC");

    jtf14.setText("STEVE SMITH   C");

    jtf15.setText("SEAN ABBOT");

    jtf16.setText("MATCHELL MARSH");

    jtf17.setText("MARCUS STONIS");

    jtf18.setText("TIM PAINE");

    jtf19.setText("MATTHEW WADE");

    jtf20.setText("PAT CUMMINS");

    jtf21.setText("MITCHELL STAC");

    jtf22.setText("ADAM ZAMPA");    
 
}
else if(jCB2.getSelectedIndex()==5)
{   
    jTA2.setText("**ENGLAND**");

    jtf12.setText("JOE ROOT   C");

    jtf13.setText("TOM BANTON   VC");

    jtf14.setText("DAN LAWRENCE");

    jtf15.setText("JAMES VINCE");

    jtf16.setText("BEN FOAKES");

    jtf17.setText("MOEEN ALI");

    jtf18.setText("JAMES ANDERSON");

    jtf19.setText("JORFA ARCHER");

    jtf20.setText("TOM CURRAN");

    jtf21.setText("MARK WOOD");

    jtf22.setText("MATT PARKINSON");    
 
} 
        // TODO add your handling code here:
    }                                        

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
ball = 120 ;
balls = ball ;
jLB1.setText("INNING ONE");
jlb2.setText("20");
        // TODO add your handling code here:
    }                                             

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                              
ball = 300 ;
balls = ball ;
jLB1.setText("INNING ONE");
jlb2.setText("50");
        // TODO add your handling code here:
    }                                             

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    r=r+1;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }
        // TODO add your handling code here:
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 r=r+2;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }

        // TODO add your handling code here:
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 r=r+3;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }

        // TODO add your handling code here:
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 r=r+4;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }

        // TODO add your handling code here:
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 r=r+5;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }


        // TODO add your handling code here:
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
 r=r+6;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }
        // TODO add your handling code here:
    }                                         

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
r=r+0;      
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }

        // TODO add your handling code here:
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
 r = r+1 ;
     run.setText(""+r);
     if(a==ball)
     {
        score1.setText(""+r); 
     }
     // TODO add your handling code here:
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
r = r+1 ;
     run.setText(""+r);
     if(a==ball)
     {
        score1.setText(""+r); 
     }

        // TODO add your handling code here:
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
 w=w+1;
      if(w<=10)
      {
          wicket.setText(""+w);
          
      }
       b=b+1;
       bb=bb+1;
       if(b==6)
       {
           a=a+1;
           b=0;
       }
       if(bb<=ball&&b<6&&w<11)
               {
                  
          run.setText(""+r);     
       overs.setText(""+a);
       
       
               }
      if(bb==ball||w>10)
       {
           bb=0;
           ball=balls;
           jLB1.setText("INNINGS TWO");
           if(c==0)
           {
           score1.setText(""+r);
           c=1;
           c++;
           }
           else
           {
           score2.setText(""+r);  
           }
           r=0;w=0;o=0;b=0;a=0;
           run.setText("");
           wicket.setText("");
           overs.setText("");
       }
        // TODO add your handling code here:
    }                                         

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
jTA3.setText("*********CRICKET SCOREBOARD************ ");
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CricScoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CricScoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CricScoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CricScoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CricScoreboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JLabel jLB1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTA1;
    private javax.swing.JTextArea jTA2;
    private javax.swing.JTextArea jTA3;
    private javax.swing.JLabel jlb2;
    private javax.swing.JTextField jtf1;
    private javax.swing.JTextField jtf10;
    private javax.swing.JTextField jtf11;
    private javax.swing.JTextField jtf12;
    private javax.swing.JTextField jtf13;
    private javax.swing.JTextField jtf14;
    private javax.swing.JTextField jtf15;
    private javax.swing.JTextField jtf16;
    private javax.swing.JTextField jtf17;
    private javax.swing.JTextField jtf18;
    private javax.swing.JTextField jtf19;
    private javax.swing.JTextField jtf2;
    private javax.swing.JTextField jtf20;
    private javax.swing.JTextField jtf21;
    private javax.swing.JTextField jtf22;
    private javax.swing.JTextField jtf3;
    private javax.swing.JTextField jtf4;
    private javax.swing.JTextField jtf5;
    private javax.swing.JTextField jtf6;
    private javax.swing.JTextField jtf7;
    private javax.swing.JTextField jtf8;
    private javax.swing.JTextField jtf9;
    private javax.swing.JTextField overs;
    private javax.swing.JTextField run;
    private javax.swing.JTextField score1;
    private javax.swing.JTextField score2;
    private javax.swing.JTextField wicket;
    // End of variables declaration                   
}
